# programmers 서울에 위치한 식당 목록 출력하기

SELECT REST_INFO.REST_ID,
        REST_INFO.REST_NAME,
        REST_INFO.FOOD_TYPE,
        REST_INFO.FAVORITES,
        REST_INFO.ADDRESS,
        ROUND(SUM(REVIEW_SCORE)/COUNT(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO LEFT JOIN REST_REVIEW
    ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE REVIEW_SCORE IS NOT NULL
    AND ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO
NATURAL JOIN REST_REVIEW
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

SELECT REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        ADDRESS,
        ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO LEFT JOIN REST_REVIEW
    ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC